name: Generate Snake Animation

on:
  schedule:
    # Runs every day at midnight
    - cron: "0 0 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository
      - uses: actions/checkout@v3

      # Generates the snake animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: devang-vala
          # These are the default colors, you can customize them
          color_snake: '#1A8CD8'
          color_dots: '#379237,#4CBB17,#7CFC00,#49FF00,#00FF7F'
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
          
      # Pushes the generated files to the output branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
